-- INSERT INTO users (username, email, password)
-- VALUES
--     ('HANNAH', 'hannah@hannah.com', 'password'),
--     ('ANDRE', 'andre@andre.com', 'password'),
--     ('JOAQUIN', 'joaquin@joaquin.com', 'password'),
--     ('BOB', 'bob@bob.com', 'hobnobbob')

-- INSERT INTO shouts (text, user_id)
-- VALUES
--     ('HELLO WORLD', 2)
--     ('WELCOME TO SHOUTER', 3)
--     ('I CANT FIND MY PHONE', 1)
--     ('HOW DO I TURN OFF CAPS LOCK', 4)